--return {
  -- Lualine.nvim
--  {
--    "nvim-lualine/lualine.nvim",
--    opts = {
--      options = {
--        theme = "auto",
--        section_separators = "",
--        component_separators = "",
--      },
--    },
--  },
--}
